---
version: 2

multi-ecosystem-groups:
  infra:
    schedule:
      interval: monthly
    commit-message:
      prefix: deps(infra)
    labels:
      - dependencies
      - infra

  apps:
    schedule:
      interval: monthly
    commit-message:
      prefix: deps(apps)
    labels:
      - dependencies
      - apps

updates:
  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: infra
    patterns:
      - '*'

  - package-ecosystem: cargo
    directory: /
    multi-ecosystem-group: apps
    patterns:
      - '*'
