---
default_language_version:
  python: python3
  node: system

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: \.gitignore

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust files
        language: system
        entry: cargo fmt
        types:
          - rust
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        description: Check Rust files
        language: system
        entry: cargo check
        types:
          - rust
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust files using Clippy
        language: system
        entry: cargo clippy
        args:
          - --
          - -D
          - clippy::all
          - -D
          - clippy::cargo
          - -D
          - clippy::pedantic
          - -A
          - clippy::cargo_common_metadata
          - -A
          - clippy::multiple_crate_versions
        types:
          - rust
        pass_filenames: false

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: e2dde74d0702d15f4f43e4f4fb93e301b4bc1e30  # frozen: 0.29.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/lyz-code/yamlfix
    rev: 47039c9bf8039e81f092c9777a1bc8be32fb7870  # frozen: 1.16.0
    hooks:
      - id: yamlfix
        args:
          - --config-file
          - .yamlfix.toml

  - repo: https://github.com/adrienverge/yamllint
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6  # frozen: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --strict

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: f295829140d25717bc79368d3f966fc1f67a824f  # frozen: v0.41.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: 4ef242b660e0f7c7c953b9d8289e302c3f49bfbc  # frozen: v0.8.1
    hooks:
      - id: taplo

  - repo: https://github.com/sirwart/ripsecrets
    rev: 033ec5192b738b6712701be920cba545c2775050  # frozen: v0.1.8
    hooks:
      - id: ripsecrets

  - repo: https://github.com/crate-ci/typos
    rev: cc99b94246254c1b3dfa6ea6111aa212b814a486  # frozen: v1.23.6
    hooks:
      - id: typos
        args: []
