---
default_language_version:
  python: python3
  node: system

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: \.gitignore

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust files
        language: system
        entry: cargo fmt
        types:
          - rust
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        description: Check Rust files
        language: system
        entry: cargo check
        types:
          - rust
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust files using Clippy
        language: system
        entry: cargo clippy
        args:
          - --
          - -D
          - clippy::all
          - -D
          - clippy::cargo
          - -D
          - clippy::pedantic
          - -A
          - clippy::cargo_common_metadata
          - -A
          - clippy::multiple_crate_versions
        types:
          - rust
        pass_filenames: false

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 54da05914997e6b04e4db33ed6757d744984c68b  # frozen: 0.33.2
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/lyz-code/yamlfix
    rev: 8072181c0f2eab9f2dd8db2eb3b9556d7cd0bd74  # frozen: 1.17.0
    hooks:
      - id: yamlfix
        args:
          - --config-file
          - .yamlfix.toml

  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      - id: yamllint
        args:
          - --strict

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 192ad822316c3a22fb3d3cc8aa6eafa0b8488360  # frozen: v0.45.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: 4ef242b660e0f7c7c953b9d8289e302c3f49bfbc  # frozen: v0.8.1
    hooks:
      - id: taplo

  - repo: https://github.com/sirwart/ripsecrets
    rev: 7d94620933e79b8acaa0cd9e60e9864b07673d86  # frozen: v0.1.11
    hooks:
      - id: ripsecrets

  - repo: https://github.com/crate-ci/typos
    rev: 3d97dc5b9833a60a62e70d5b56af2cc7ddd522f6  # frozen: v1
    hooks:
      - id: typos
        args: []
