---
name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659  # v1.17.0
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all --check

  yara:
    name: Build YARA
    needs: lint

    uses: ./.github/workflows/yara.yaml
    with:
      runs-on: ubuntu-24.04

  clippy:
    name: Clippy
    needs: yara

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Download YARA
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: ${{ needs.yara.outputs.artifacts }}
          path: .yara

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659  # v1.17.0
        with:
          components: clippy
          cache-key: x86_64-unknown-linux-gnu

      - name: Run Clippy
        run: >
          cargo clippy --locked --all-targets -- \
            -D warnings \
            -D clippy::all \
            -D clippy::cargo \
            -D clippy::pedantic \
            -A clippy::cargo_common_metadata \
            -A clippy::multiple_crate_versions
        env:
          YARA_INCLUDE_DIR: ${{ github.workspace }}/.yara/${{ needs.yara.outputs.include-dir }}
          YARA_LIBRARY_PATH: ${{ github.workspace }}/.yara/${{ needs.yara.outputs.library-path }}

  test:
    name: Test
    needs:
      - yara

    strategy:
      matrix:
        triple:
          - runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.triple.runs-on }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Download YARA
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: ${{ needs.yara.outputs.artifacts }}
          path: .yara

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659  # v1.17.0
        with:
          cache-key: ${{ matrix.triple.target }}

      - name: Run tests
        env:
          RUST_BACKTRACE: full
          YARA_INCLUDE_DIR: ${{ github.workspace }}/.yara/${{ needs.yara.outputs.include-dir }}
          YARA_LIBRARY_PATH: ${{ github.workspace }}/.yara/${{ needs.yara.outputs.library-path }}
        run: cargo test --locked --all-targets --no-fail-fast

  docs-build:
    name: Build documentation
    needs:
      - yara
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659  # v1.17.0
        with:
          cache-key: x86_64-unknown-linux-gnu

      - name: Download YARA
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: ${{ needs.yara.outputs.artifacts }}
          path: .yara

      - name: Build docs with cargo
        run: cargo doc --locked --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings
          YARA_INCLUDE_DIR: ${{ github.workspace }}/.yara/${{ needs.yara.outputs.include-dir }}
          YARA_LIBRARY_PATH: ${{ github.workspace }}/.yara/${{ needs.yara.outputs.library-path }}

      # `.lock` is set to to rw-------, which causes actions/deploy-pages to fail
      # because it's expecting all files to be at least rw-r--r--
      - name: Remove '.lock' file
        run: rm ./target/doc/.lock

      # `cargo doc` builds the docs without a top level `index.html`, so add
      # a barebones one to redirect to the generated one.
      - name: Add redirect index.html
        run: echo '<meta http-equiv="refresh" content="0; url=dragonfly_client_rs">' > target/doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5.0.0
        with:
          path: ./target/doc
          include-hidden-files: true

  docs-deploy:
    name: Deploy documentation
    needs: docs-build

    if: github.ref == 'refs/heads/main'

    # Permissions needed to deploy to GitHub Pages.
    permissions:
      pages: write  # Deploy the generated documentation to GitHub Pages.
      id-token: write  # Authenticate the deployment to GitHub Pages.

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04

    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128  # v5.0.0
