---
name: YARA

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner image
        required: true
        type: string
      version:
        description: YARA version
        default: 4.5.4
        required: false
        type: string
    outputs:
      artifacts:
        description: YARA Artifacts
        value: ${{ jobs.yara.outputs.artifacts }}
      include-dir:
        description: YARA Includes Directory
        value: libyara/include
      library-path:
        description: YARA Library Path
        value: .libs

defaults:
  run:
    shell: bash

env:
  YARA_VERSION: ${{ inputs.version }}

permissions:
  contents: read

jobs:
  yara:
    name: Compile YARA
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Cache YARA
        id: cache-yara
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          key: ${{ github.ref }}-yara-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
          path: yara-${{ inputs.version }}

      - name: Compile YARA
        run: |
          #/usr/bin/env bash
          set -e

          curl -sL \
              https://github.com/VirusTotal/yara/archive/refs/tags/v$YARA_VERSION.tar.gz \
              -o yara-$YARA_VERSION.tar.gz
          tar -xzf yara-$YARA_VERSION.tar.gz
          cd yara-$YARA_VERSION
          ./bootstrap.sh
          ./configure
          make
        if: steps.cache-yara.outputs.cache-hit != 'true' && runner.os == 'Linux'

      - name: Upload YARA
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          if-no-files-found: error
          name: yara-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            yara-${{ inputs.version }}/libyara/include/yara
            yara-${{ inputs.version }}/libyara/include/yara.h
            yara-${{ inputs.version }}/.libs/libyara*
          include-hidden-files: true
          retention-days: 1
          overwrite: true

    outputs:
      artifacts: yara-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
