---
name: YARA

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner image
        required: true
        type: string
      version:
        description: YARA version
        default: 4.5.4
        required: false
        type: string
    outputs:
      artifacts:
        description: YARA Artifacts
        value: ${{ jobs.output.outputs.artifacts }}
      include-dir:
        description: YARA Includes Directory
        value: libyara/include
      library-path:
        description: YARA Library Path
        value: .libs

defaults:
  run:
    shell: bash

env:
  YARA_VERSION: ${{ inputs.version }}

permissions:
  contents: read

jobs:
  yara:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Cache YARA
        id: cache-yara
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          key: yara-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
          path: yara-${{ inputs.version }}

      - name: Compile YARA
        run: |
          #/usr/bin/env bash
          set -e

          curl -sL \
              https://github.com/VirusTotal/yara/archive/refs/tags/v$YARA_VERSION.tar.gz \
              -o yara-$YARA_VERSION.tar.gz
          tar -xzf yara-$YARA_VERSION.tar.gz
          cd yara-$YARA_VERSION
          ./bootstrap.sh
          ./configure
          make
        if: steps.cache-yara.outputs.cache-hit != 'true' && runner.os == 'Linux'

      - name: Upload YARA
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4  # v5.0.0
        with:
          if-no-files-found: error
          name: yara-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            yara-${{ inputs.version }}/libyara/include/yara
            yara-${{ inputs.version }}/libyara/include/yara.h
            yara-${{ inputs.version }}/.libs/libyara*
          include-hidden-files: true
          retention-days: 1
          overwrite: true

    outputs:
      artifacts: yara-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}

  output:
    needs: yara

    runs-on: ubuntu-22.04
    steps:
      - name: Write Matrix Output
        id: write
        uses: cloudposse/github-action-matrix-outputs-write@ed06cf3a6bf23b8dce36d1cf0d63123885bb8375  # v1.0.0
        with:
          matrix-step-name: yara
          matrix-key: ${{ inputs.runs-on }}
          outputs: |-
            artifacts: ${{ needs.yara.outputs.artifacts }}

    outputs:
      artifacts: ${{ fromJson(steps.write.outputs.result).artifacts }}
