---
name: YARA

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner image
        required: true
        type: string
    outputs:
      artifacts:
        description: YARA Artifacts
        value: ${{ jobs.yara.outputs.artifacts }}
      include-dir:
        description: YARA Includes Directory
        value: libyara/include
      library-path:
        description: YARA Library Path
        value: .libs

defaults:
  run:
    shell: bash

env:
  YARA_COMMIT: 7ff39042be5c63682a037e13a75221d59393cf8b
  YARA_SHA256: 70e9d13905f5687a2c2731b64a8073001d5f1909967f81937ab27fe10006ec97
  YARA_VERSION: 4.5.4

permissions:
  contents: read

jobs:
  yara:
    name: Compile YARA
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Cache YARA
        id: cache-yara
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          key: yara-${{ env.YARA_COMMIT }}-${{ runner.os }}-${{ runner.arch }}
          path: yara-${{ env.YARA_COMMIT }}

      - name: Compile YARA
        run: |
          set -euo pipefail

          archive_filename="yara-$YARA_COMMIT.tar.gz"
          curl --fail --location --silent --show-error \
            "https://github.com/VirusTotal/yara/archive/$YARA_COMMIT.tar.gz" \
            --output "$archive_filename"
          printf '%s  %s\n' "$YARA_SHA256" "$archive_filename" \
            | sha256sum --check --strict
          tar -xzf "$archive_filename"
          cd "yara-$YARA_COMMIT"
          ./bootstrap.sh
          ./configure
          make
        if: steps.cache-yara.outputs.cache-hit != 'true' && runner.os == 'Linux'

      - name: Upload YARA
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          if-no-files-found: error
          name: yara-${{ env.YARA_VERSION }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            yara-${{ env.YARA_COMMIT }}/libyara/include/yara
            yara-${{ env.YARA_COMMIT }}/libyara/include/yara.h
            yara-${{ env.YARA_COMMIT }}/.libs/libyara*
          include-hidden-files: true
          retention-days: 1
          overwrite: true

    outputs:
      artifacts: yara-${{ env.YARA_VERSION }}-${{ runner.os }}-${{ runner.arch }}
